### ISSUE TITLE
Day | Night theme bugged

### ISSUE THREAD

**Issue by JairDavid** [leoNavarro95/my-front-end-portfolio#5]
If we go to the contact view and I try to change the theme, throws"Page not found"
![image](https://user-images.githubusercontent.com/67834146/166121184-0558795f-274f-4ec4-bc39-3b9a4717fa38.png)

![image](https://user-images.githubusercontent.com/67834146/166121194-33b90efc-1c90-4c32-927a-178e1c9955bb.png)

![image](https://user-images.githubusercontent.com/67834146/166121201-7b0e2859-538e-4655-928c-46954d3976f5.png)

**Comment by leoNavarro95** [comment]
I am try to solve that some weeks ago, and I couldn't. When I run the project locally this bug doesn't happen. 
I think it's something about routes in the server. After the 404 error if page is refreshed then it works

Thanks for this issue

**Comment by Krb0** [comment]
Looks like it's a common issue when using netlify and vue. 
[This might be the solution](https://forum.vuejs.org/t/page-not-found-when-refreshing-the-page/120134) 
Hope it works 👌

**Comment by leoNavarro95** [comment]
> Looks like it's a common issue when using netlify and vue. [This might be the solution](https://forum.vuejs.org/t/page-not-found-when-refreshing-the-page/120134) Hope it works 👌

I'm pretty sure this is the solution, thanks a lot for the help I really appreciate it, I'm going to work in this immediately

**Comment by leoNavarro95** [comment]
Bug solved!!! It was really easy just create a netlify.toml file in the projects root directory and inside copy this:

`
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`
And that's it!!!

@Krb0 thanks for leading me to the solution
